[versions]
android-gradle-plugin = "8.3.0-alpha03"
detekt = "1.23.1"
kotlin = "1.9.10"

compose-foundation = "1.5.1"
compose-material3 = "1.1.1"
compose-ui = "1.1.5.1"

[libraries]
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose-foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }

kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

[bundles]
compose-tooling = [
    "compose-ui-test-manifest",
    "compose-ui-tooling"
]
